# Generated by Django 5.2.8 on 2026-01-11 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(help_text="Language code (e.g., 'en', 'ru', 'de')", max_length=10, primary_key=True, serialize=False)),
                ('flag', models.FileField(blank=True, help_text='Flag image (SVG preferred)', upload_to='flags/')),
                ('name', models.CharField(help_text="Language name (e.g., 'English', 'Russian')", max_length=100)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.UUIDField(help_text='User UUID from auth service', primary_key=True, serialize=False)),
                ('currency_code', models.CharField(default='EUR', help_text="Preferred currency code (e.g., 'EUR', 'USD')", max_length=3)),
                ('measurement_units', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', help_text='Preferred measurement system', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', help_text='UI theme preference', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_language', models.ForeignKey(blank=True, help_text='Primary app language (default: English)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_app_language', to='profiles.language')),
                ('understands', models.ManyToManyField(blank=True, help_text='Languages the user understands', related_name='users_who_understand', to='profiles.language')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.UUIDField(db_index=True, help_text='UUID of the user who follows/blocks')),
                ('following_id', models.UUIDField(db_index=True, help_text='UUID of the user being followed/blocked')),
                ('status', models.CharField(choices=[('neutral', 'Neutral'), ('following', 'Following'), ('blocked', 'Blocked')], default='neutral', help_text='Relationship status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Relationship',
                'verbose_name_plural': 'User Relationships',
                'indexes': [models.Index(fields=['follower_id', 'status'], name='profiles_us_followe_89ca4d_idx'), models.Index(fields=['following_id', 'status'], name='profiles_us_followi_75ec41_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower_id', 'following_id'), name='unique_relationship'), models.CheckConstraint(condition=models.Q(('follower_id', models.F('following_id')), _negated=True), name='no_self_relationship')],
            },
        ),
    ]
