# Generated by Django 5.2.8 on 2026-01-13 23:31

import stapel_core.django.cdn.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=stapel_core.django.cdn.fields.CdnImageField(blank=True, help_text='CDN avatar image reference (avatar/hash)', image_type='avatar', null=True),
        ),
    ]
