# Generated by Django 5.2.8 on 2026-01-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_avatar_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text="User's display name", max_length=100),
        ),
    ]
