# Generated by Django 5.2.8 on 2026-01-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_add_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_translate_content',
            field=models.BooleanField(default=False, help_text='Automatically translate content'),
        ),
        migrations.AddField(
            model_name='profile',
            name='essential_cookies_accepted',
            field=models.BooleanField(default=False, help_text='User accepted essential cookies'),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_device_language',
            field=models.BooleanField(default=True, help_text='Use device language for app UI'),
        ),
    ]
