# Generated by Django 5.2.8 on 2026-01-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_add_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_id',
            field=models.IntegerField(blank=True, help_text="User's location ID from geo service", null=True),
        ),
    ]
