# Generated by Django 5.2.8 on 2026-02-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_add_location_display_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='initial_setup_passed',
            field=models.BooleanField(default=False, help_text='User completed initial profile setup'),
        ),
    ]
