# Generated by Django 5.2.8 on 2026-02-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_add_initial_setup_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this language is available for selection'),
        ),
    ]
