# Generated by Django 5.2.8 on 2026-02-09 02:01
#
# stapel: contract-phase
# verified: this migration shipped in stapel-profiles' first commit/release
# (v0.2.0+; extracted from the monolith) — no released version of this
# package predates it, and the current models.py already declares
# display_name = CharField(max_length=35, ...), matching this narrowed width.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_add_language_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text="User's display name", max_length=35),
        ),
    ]
