# Generated by Django 6.0.2 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_display_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_system',
            field=models.BooleanField(default=True),
        ),
    ]
