# Generated by Django 6.0.2 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_add_notification_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_detected_language',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Last detected language from Accept-Language header',
                max_length=10,
            ),
        ),
    ]
