# Generated by Django 6.0.6 on 2026-07-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_drop_orphan_rating_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_messages',
            field=models.BooleanField(default=True, help_text='Receive message notifications via email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_system',
            field=models.BooleanField(default=True, help_text='Receive system notifications via email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='push_messages',
            field=models.BooleanField(default=True, help_text='Receive message notifications via push'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='push_system',
            field=models.BooleanField(default=True, help_text='Receive system notifications via push'),
        ),
    ]
