# Generated by Django 6.0.7 on 2026-07-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_profile_email_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency_code',
            field=models.CharField(default='USD', help_text="Preferred currency code (e.g., 'USD', 'EUR')", max_length=3),
        ),
    ]
