# Generated by Django 6.0.7 on 2026-08-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_profile_display_name_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='merged_into',
            field=models.UUIDField(blank=True, db_index=True, help_text="The surviving account this profile's owner was folded into. Non-NULL means the row is ARCHIVED: the survivor's own profile is the live one and this row is history, kept rather than deleted. NULL for every live profile.", null=True),
        ),
    ]
