# Generated by Django 6.0.7 on 2026-09-14
#
# Expand-only: max_length 35 -> 80. A client fleet's storefront seed hit
# 400 on a 36-char shop display name ("Магазин электроники «Гаджет
# Маркет»"); quoted shop names plus a legal form (ООО/ИП/…) regularly
# clear 35 chars. Widening a CharField's max_length is a metadata-only
# change on every backend this module targets (Postgres/SQLite/MySQL
# VARCHAR) — no data migration, no column rewrite, existing rows already
# satisfy the wider bound.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text="User's display name.", max_length=80),
        ),
    ]
